### ISSUE TITLE
Receiving commands appears to break when using a CrLf (\r\n) line ending

### ISSUE THREAD

**Issue by DeflateAwning** [sq8vps/vp-digi#24] opened 2023-08-21 18:53 UTC
Steps to reproduce:

1. Turn on device, flash. connect to UART1 with a 9600 uart-to-usb converter. Using RealTerm.
2. Send `monitor\n`, where `\n` means the newline character (and not those literal characters).
3. Send `version\n`. Everything works.
4. Send `version\n\r`. Everything works fine. This is a weird one that probably rarely happens.
5. Send `version\r`. Everything works fine.
6. Send `version\r\n`. Observe no response. Observe that device goes unresponsive.

It appears that after step 5, the device requires a reboot to function.

This isn't the worst bug, but thought it was worth pointing out. In the README or on your website, you should mention the expected EOL character (esp. if you don't fix this behaviour).

**Comment by sq8vps** [comment] 2023-08-30 12:20
Resolved in 1.3.0, or at least I was unable to reproduce the issue

**Closed by sq8vps** 2023-08-30 12:20 UTC
